/*******************************************************************************
 * Copyright (C) 2011 Julio Leite
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

package test.xml;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import leitej.exception.XmlInvalidLtException;
import leitej.xml.XmlConsumer;

public class JXmlConsumer {

	private String fileName;

	@Before
	public void setUp() throws Exception {
		this.fileName = "testJXmlConsumer.lixo.xml";
	}

	@After
	public void tearDown() throws Exception {
		(new File(this.fileName)).delete();
	}

	@Test
	public void testXML0() {
		final String[] xml0 = { "<?xml version=\"1.0\" encoding=\"UTF8\"?>", "<elementName att=\"value\">",
				"</elementName>" };
		try {
			write2file(xml0);
			final long[] r = testConsume();
			assertTrue(r[0] == 1);
			assertTrue(r[1] == 1);
			assertTrue(r[2] == 0);
		} catch (final IOException e) {
			e.printStackTrace();
			fail(e.toString());
		} catch (final XmlInvalidLtException e) {
			e.printStackTrace();
			fail(e.toString());
		}
	}

	@Test
	public void testXML1() {
		String[] xml1 = {
				"<?xml version=\"1.0\" encoding=\"UTF8\"?>",
				"<elementName att=\"value\">",
				"	<elementName att=\"value\">",
				"		<elementName att=\"value\">",
				"			<elementName att=\"value\">",
				"				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">1</elementName>",
				"					</elementName>",
				"				</elementName>",
				"			</elementName>",
				"		</elementName>",
				"	</elementName>",
				"</elementName>"};
		try {
			write2file(xml1);
			final long[] r = testConsume();
			assertTrue(r[0] == 7);
			assertTrue(r[1] == 7);
			assertTrue(r[2] == 1);
		} catch (final IOException e) {
			e.printStackTrace();
			fail(e.toString());
		} catch (final XmlInvalidLtException e) {
			e.printStackTrace();
			fail(e.toString());
		}
	}

	@Test
	public void testXMLseq() {
		final String[] xmlseq = { "<?xml version=\"1.0\" encoding=\"UTF8\"?>", "<elementName att=\"value\">",
				"	<elementName att=\"value\">", "		<elementName att=\"value\">",
				"			<elementName att=\"value\">", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">1</elementName>",
				"						<elementName att=\"value\">2</elementName>",
				"						<elementName att=\"value\">3</elementName>",
				"						<elementName att=\"value\">4</elementName>",
				"						<elementName att=\"value\">5</elementName>",
				"						<elementName att=\"value\">6</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">7</elementName>",
				"						<elementName att=\"value\">8</elementName>",
				"						<elementName att=\"value\">9</elementName>",
				"						<elementName att=\"value\">10</elementName>",
				"						<elementName att=\"value\">11</elementName>",
				"						<elementName att=\"value\">12</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">13</elementName>",
				"						<elementName att=\"value\">14</elementName>",
				"						<elementName att=\"value\">15</elementName>",
				"						<elementName att=\"value\">16</elementName>",
				"						<elementName att=\"value\">17</elementName>",
				"						<elementName att=\"value\">18</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">19</elementName>",
				"						<elementName att=\"value\">20</elementName>",
				"						<elementName att=\"value\">21</elementName>",
				"						<elementName att=\"value\">22</elementName>",
				"						<elementName att=\"value\">23</elementName>",
				"						<elementName att=\"value\">24</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">25</elementName>",
				"						<elementName att=\"value\">26</elementName>",
				"						<elementName att=\"value\">27</elementName>",
				"						<elementName att=\"value\">28</elementName>",
				"						<elementName att=\"value\">29</elementName>",
				"						<elementName att=\"value\">30</elementName>", "					</elementName>",
				"				</elementName>", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">31</elementName>",
				"						<elementName att=\"value\">32</elementName>",
				"						<elementName att=\"value\">33</elementName>",
				"						<elementName att=\"value\">34</elementName>",
				"						<elementName att=\"value\">35</elementName>",
				"						<elementName att=\"value\">36</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">37</elementName>",
				"						<elementName att=\"value\">38</elementName>",
				"						<elementName att=\"value\">39</elementName>",
				"						<elementName att=\"value\">40</elementName>",
				"						<elementName att=\"value\">41</elementName>",
				"						<elementName att=\"value\">42</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">43</elementName>",
				"						<elementName att=\"value\">44</elementName>",
				"						<elementName att=\"value\">45</elementName>",
				"						<elementName att=\"value\">46</elementName>",
				"						<elementName att=\"value\">47</elementName>",
				"						<elementName att=\"value\">48</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">49</elementName>",
				"						<elementName att=\"value\">50</elementName>",
				"						<elementName att=\"value\">51</elementName>",
				"						<elementName att=\"value\">52</elementName>",
				"						<elementName att=\"value\">53</elementName>",
				"						<elementName att=\"value\">54</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">55</elementName>",
				"						<elementName att=\"value\">56</elementName>",
				"						<elementName att=\"value\">57</elementName>",
				"						<elementName att=\"value\">58</elementName>",
				"						<elementName att=\"value\">59</elementName>",
				"						<elementName att=\"value\">60</elementName>", "					</elementName>",
				"				</elementName>", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">61</elementName>",
				"						<elementName att=\"value\">62</elementName>",
				"						<elementName att=\"value\">63</elementName>",
				"						<elementName att=\"value\">64</elementName>",
				"						<elementName att=\"value\">65</elementName>",
				"						<elementName att=\"value\">66</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">67</elementName>",
				"						<elementName att=\"value\">68</elementName>",
				"						<elementName att=\"value\">69</elementName>",
				"						<elementName att=\"value\">70</elementName>",
				"						<elementName att=\"value\">71</elementName>",
				"						<elementName att=\"value\">72</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">73</elementName>",
				"						<elementName att=\"value\">74</elementName>",
				"						<elementName att=\"value\">75</elementName>",
				"						<elementName att=\"value\">76</elementName>",
				"						<elementName att=\"value\">77</elementName>",
				"						<elementName att=\"value\">78</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">79</elementName>",
				"						<elementName att=\"value\">80</elementName>",
				"						<elementName att=\"value\">81</elementName>",
				"						<elementName att=\"value\">82</elementName>",
				"						<elementName att=\"value\">83</elementName>",
				"						<elementName att=\"value\">84</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">85</elementName>",
				"						<elementName att=\"value\">86</elementName>",
				"						<elementName att=\"value\">87</elementName>",
				"						<elementName att=\"value\">88</elementName>",
				"						<elementName att=\"value\">89</elementName>",
				"						<elementName att=\"value\">90</elementName>", "					</elementName>",
				"				</elementName>", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">91</elementName>",
				"						<elementName att=\"value\">92</elementName>",
				"						<elementName att=\"value\">93</elementName>",
				"						<elementName att=\"value\">94</elementName>",
				"						<elementName att=\"value\">95</elementName>",
				"						<elementName att=\"value\">96</elementName>", "					</elementName>",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">97</elementName>",
				"						<elementName att=\"value\">98</elementName>",
				"						<elementName att=\"value\">99</elementName>",
				"						<elementName att=\"value\">100</elementName>",
				"						<elementName att=\"value\">101</elementName>",
				"						<elementName att=\"value\">102</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">103</elementName>",
				"						<elementName att=\"value\">104</elementName>",
				"						<elementName att=\"value\">105</elementName>",
				"						<elementName att=\"value\">106</elementName>",
				"						<elementName att=\"value\">107</elementName>",
				"						<elementName att=\"value\">108</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">109</elementName>",
				"						<elementName att=\"value\">110</elementName>",
				"						<elementName att=\"value\">111</elementName>",
				"						<elementName att=\"value\">112</elementName>",
				"						<elementName att=\"value\">113</elementName>",
				"						<elementName att=\"value\">114</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">115</elementName>",
				"						<elementName att=\"value\">116</elementName>",
				"						<elementName att=\"value\">117</elementName>",
				"						<elementName att=\"value\">118</elementName>",
				"						<elementName att=\"value\">119</elementName>",
				"						<elementName att=\"value\">120</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"			<elementName att=\"value\">", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">121</elementName>",
				"						<elementName att=\"value\">122</elementName>",
				"						<elementName att=\"value\">123</elementName>",
				"						<elementName att=\"value\">124</elementName>",
				"						<elementName att=\"value\">125</elementName>",
				"						<elementName att=\"value\">126</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">127</elementName>",
				"						<elementName att=\"value\">128</elementName>",
				"						<elementName att=\"value\">129</elementName>",
				"						<elementName att=\"value\">130</elementName>",
				"						<elementName att=\"value\">131</elementName>",
				"						<elementName att=\"value\">132</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">133</elementName>",
				"						<elementName att=\"value\">134</elementName>",
				"						<elementName att=\"value\">135</elementName>",
				"						<elementName att=\"value\">136</elementName>",
				"						<elementName att=\"value\">137</elementName>",
				"						<elementName att=\"value\">138</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">139</elementName>",
				"						<elementName att=\"value\">140</elementName>",
				"						<elementName att=\"value\">141</elementName>",
				"						<elementName att=\"value\">142</elementName>",
				"						<elementName att=\"value\">143</elementName>",
				"						<elementName att=\"value\">144</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">145</elementName>",
				"						<elementName att=\"value\">146</elementName>",
				"						<elementName att=\"value\">147</elementName>",
				"						<elementName att=\"value\">148</elementName>",
				"						<elementName att=\"value\">149</elementName>",
				"						<elementName att=\"value\">150</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">151</elementName>",
				"						<elementName att=\"value\">152</elementName>",
				"						<elementName att=\"value\">153</elementName>",
				"						<elementName att=\"value\">154</elementName>",
				"						<elementName att=\"value\">155</elementName>",
				"						<elementName att=\"value\">156</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">157</elementName>",
				"						<elementName att=\"value\">158</elementName>",
				"						<elementName att=\"value\">159</elementName>",
				"						<elementName att=\"value\">160</elementName>",
				"						<elementName att=\"value\">161</elementName>",
				"						<elementName att=\"value\">162</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">163</elementName>",
				"						<elementName att=\"value\">164</elementName>",
				"						<elementName att=\"value\">165</elementName>",
				"						<elementName att=\"value\">166</elementName>",
				"						<elementName att=\"value\">167</elementName>",
				"						<elementName att=\"value\">168</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">169</elementName>",
				"						<elementName att=\"value\">170</elementName>",
				"						<elementName att=\"value\">171</elementName>",
				"						<elementName att=\"value\">172</elementName>",
				"						<elementName att=\"value\">173</elementName>",
				"						<elementName att=\"value\">174</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">175</elementName>",
				"						<elementName att=\"value\">176</elementName>",
				"						<elementName att=\"value\">177</elementName>",
				"						<elementName att=\"value\">178</elementName>",
				"						<elementName att=\"value\">179</elementName>",
				"						<elementName att=\"value\">180</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">181</elementName>",
				"						<elementName att=\"value\">182</elementName>",
				"						<elementName att=\"value\">183</elementName>",
				"						<elementName att=\"value\">184</elementName>",
				"						<elementName att=\"value\">185</elementName>",
				"						<elementName att=\"value\">186</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">187</elementName>",
				"						<elementName att=\"value\">188</elementName>",
				"						<elementName att=\"value\">189</elementName>",
				"						<elementName att=\"value\">190</elementName>",
				"						<elementName att=\"value\">191</elementName>",
				"						<elementName att=\"value\">192</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">193</elementName>",
				"						<elementName att=\"value\">194</elementName>",
				"						<elementName att=\"value\">195</elementName>",
				"						<elementName att=\"value\">196</elementName>",
				"						<elementName att=\"value\">197</elementName>",
				"						<elementName att=\"value\">198</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">199</elementName>",
				"						<elementName att=\"value\">200</elementName>",
				"						<elementName att=\"value\">201</elementName>",
				"						<elementName att=\"value\">202</elementName>",
				"						<elementName att=\"value\">203</elementName>",
				"						<elementName att=\"value\">204</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">205</elementName>",
				"						<elementName att=\"value\">206</elementName>",
				"						<elementName att=\"value\">207</elementName>",
				"						<elementName att=\"value\">208</elementName>",
				"						<elementName att=\"value\">209</elementName>",
				"						<elementName att=\"value\">210</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">211</elementName>",
				"						<elementName att=\"value\">212</elementName>",
				"						<elementName att=\"value\">213</elementName>",
				"						<elementName att=\"value\">214</elementName>",
				"						<elementName att=\"value\">215</elementName>",
				"						<elementName att=\"value\">216</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">217</elementName>",
				"						<elementName att=\"value\">218</elementName>",
				"						<elementName att=\"value\">219</elementName>",
				"						<elementName att=\"value\">220</elementName>",
				"						<elementName att=\"value\">221</elementName>",
				"						<elementName att=\"value\">222</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">223</elementName>",
				"						<elementName att=\"value\">224</elementName>",
				"						<elementName att=\"value\">225</elementName>",
				"						<elementName att=\"value\">226</elementName>",
				"						<elementName att=\"value\">227</elementName>",
				"						<elementName att=\"value\">228</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">229</elementName>",
				"						<elementName att=\"value\">230</elementName>",
				"						<elementName att=\"value\">231</elementName>",
				"						<elementName att=\"value\">232</elementName>",
				"						<elementName att=\"value\">233</elementName>",
				"						<elementName att=\"value\">234</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">235</elementName>",
				"						<elementName att=\"value\">236</elementName>",
				"						<elementName att=\"value\">237</elementName>",
				"						<elementName att=\"value\">238</elementName>",
				"						<elementName att=\"value\">239</elementName>",
				"						<elementName att=\"value\">240</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"			<elementName att=\"value\">", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">241</elementName>",
				"						<elementName att=\"value\">242</elementName>",
				"						<elementName att=\"value\">243</elementName>",
				"						<elementName att=\"value\">244</elementName>",
				"						<elementName att=\"value\">245</elementName>",
				"						<elementName att=\"value\">246</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">247</elementName>",
				"						<elementName att=\"value\">248</elementName>",
				"						<elementName att=\"value\">249</elementName>",
				"						<elementName att=\"value\">250</elementName>",
				"						<elementName att=\"value\">251</elementName>",
				"						<elementName att=\"value\">252</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">253</elementName>",
				"						<elementName att=\"value\">254</elementName>",
				"						<elementName att=\"value\">255</elementName>",
				"						<elementName att=\"value\">256</elementName>",
				"						<elementName att=\"value\">257</elementName>",
				"						<elementName att=\"value\">258</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">259</elementName>",
				"						<elementName att=\"value\">260</elementName>",
				"						<elementName att=\"value\">261</elementName>",
				"						<elementName att=\"value\">262</elementName>",
				"						<elementName att=\"value\">263</elementName>",
				"						<elementName att=\"value\">264</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">265</elementName>",
				"						<elementName att=\"value\">266</elementName>",
				"						<elementName att=\"value\">267</elementName>",
				"						<elementName att=\"value\">268</elementName>",
				"						<elementName att=\"value\">269</elementName>",
				"						<elementName att=\"value\">270</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">271</elementName>",
				"						<elementName att=\"value\">272</elementName>",
				"						<elementName att=\"value\">273</elementName>",
				"						<elementName att=\"value\">274</elementName>",
				"						<elementName att=\"value\">275</elementName>",
				"						<elementName att=\"value\">276</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">277</elementName>",
				"						<elementName att=\"value\">278</elementName>",
				"						<elementName att=\"value\">279</elementName>",
				"						<elementName att=\"value\">280</elementName>",
				"						<elementName att=\"value\">281</elementName>",
				"						<elementName att=\"value\">282</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">283</elementName>",
				"						<elementName att=\"value\">284</elementName>",
				"						<elementName att=\"value\">285</elementName>",
				"						<elementName att=\"value\">286</elementName>",
				"						<elementName att=\"value\">287</elementName>",
				"						<elementName att=\"value\">288</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">289</elementName>",
				"						<elementName att=\"value\">290</elementName>",
				"						<elementName att=\"value\">291</elementName>",
				"						<elementName att=\"value\">292</elementName>",
				"						<elementName att=\"value\">293</elementName>",
				"						<elementName att=\"value\">294</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">295</elementName>",
				"						<elementName att=\"value\">296</elementName>",
				"						<elementName att=\"value\">297</elementName>",
				"						<elementName att=\"value\">298</elementName>",
				"						<elementName att=\"value\">299</elementName>",
				"						<elementName att=\"value\">300</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">301</elementName>",
				"						<elementName att=\"value\">302</elementName>",
				"						<elementName att=\"value\">303</elementName>",
				"						<elementName att=\"value\">304</elementName>",
				"						<elementName att=\"value\">305</elementName>",
				"						<elementName att=\"value\">306</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">307</elementName>",
				"						<elementName att=\"value\">308</elementName>",
				"						<elementName att=\"value\">309</elementName>",
				"						<elementName att=\"value\">310</elementName>",
				"						<elementName att=\"value\">311</elementName>",
				"						<elementName att=\"value\">312</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">313</elementName>",
				"						<elementName att=\"value\">314</elementName>",
				"						<elementName att=\"value\">315</elementName>",
				"						<elementName att=\"value\">316</elementName>",
				"						<elementName att=\"value\">317</elementName>",
				"						<elementName att=\"value\">318</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">319</elementName>",
				"						<elementName att=\"value\">320</elementName>",
				"						<elementName att=\"value\">321</elementName>",
				"						<elementName att=\"value\">322</elementName>",
				"						<elementName att=\"value\">323</elementName>",
				"						<elementName att=\"value\">324</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">325</elementName>",
				"						<elementName att=\"value\">326</elementName>",
				"						<elementName att=\"value\">327</elementName>",
				"						<elementName att=\"value\">328</elementName>",
				"						<elementName att=\"value\">329</elementName>",
				"						<elementName att=\"value\">330</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">331</elementName>",
				"						<elementName att=\"value\">332</elementName>",
				"						<elementName att=\"value\">333</elementName>",
				"						<elementName att=\"value\">334</elementName>",
				"						<elementName att=\"value\">335</elementName>",
				"						<elementName att=\"value\">336</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">337</elementName>",
				"						<elementName att=\"value\">338</elementName>",
				"						<elementName att=\"value\">339</elementName>",
				"						<elementName att=\"value\">340</elementName>",
				"						<elementName att=\"value\">341</elementName>",
				"						<elementName att=\"value\">342</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">343</elementName>",
				"						<elementName att=\"value\">344</elementName>",
				"						<elementName att=\"value\">345</elementName>",
				"						<elementName att=\"value\">346</elementName>",
				"						<elementName att=\"value\">347</elementName>",
				"						<elementName att=\"value\">348</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">349</elementName>",
				"						<elementName att=\"value\">350</elementName>",
				"						<elementName att=\"value\">351</elementName>",
				"						<elementName att=\"value\">352</elementName>",
				"						<elementName att=\"value\">353</elementName>",
				"						<elementName att=\"value\">354</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">355</elementName>",
				"						<elementName att=\"value\">356</elementName>",
				"						<elementName att=\"value\">357</elementName>",
				"						<elementName att=\"value\">358</elementName>",
				"						<elementName att=\"value\">359</elementName>",
				"						<elementName att=\"value\">360</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"		</elementName>", "		<elementName att=\"value\">", "			<elementName att=\"value\">",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">361</elementName>",
				"						<elementName att=\"value\">362</elementName>",
				"						<elementName att=\"value\">363</elementName>",
				"						<elementName att=\"value\">364</elementName>",
				"						<elementName att=\"value\">365</elementName>",
				"						<elementName att=\"value\">366</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">367</elementName>",
				"						<elementName att=\"value\">368</elementName>",
				"						<elementName att=\"value\">369</elementName>",
				"						<elementName att=\"value\">370</elementName>",
				"						<elementName att=\"value\">371</elementName>",
				"						<elementName att=\"value\">372</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">373</elementName>",
				"						<elementName att=\"value\">374</elementName>",
				"						<elementName att=\"value\">375</elementName>",
				"						<elementName att=\"value\">376</elementName>",
				"						<elementName att=\"value\">377</elementName>",
				"						<elementName att=\"value\">378</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">379</elementName>",
				"						<elementName att=\"value\">380</elementName>",
				"						<elementName att=\"value\">381</elementName>",
				"						<elementName att=\"value\">382</elementName>",
				"						<elementName att=\"value\">383</elementName>",
				"						<elementName att=\"value\">384</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">385</elementName>",
				"						<elementName att=\"value\">386</elementName>",
				"						<elementName att=\"value\">387</elementName>",
				"						<elementName att=\"value\">388</elementName>",
				"						<elementName att=\"value\">389</elementName>",
				"						<elementName att=\"value\">390</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">391</elementName>",
				"						<elementName att=\"value\">392</elementName>",
				"						<elementName att=\"value\">393</elementName>",
				"						<elementName att=\"value\">394</elementName>",
				"						<elementName att=\"value\">395</elementName>",
				"						<elementName att=\"value\">396</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">397</elementName>",
				"						<elementName att=\"value\">398</elementName>",
				"						<elementName att=\"value\">399</elementName>",
				"						<elementName att=\"value\">400</elementName>",
				"						<elementName att=\"value\">401</elementName>",
				"						<elementName att=\"value\">402</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">403</elementName>",
				"						<elementName att=\"value\">404</elementName>",
				"						<elementName att=\"value\">405</elementName>",
				"						<elementName att=\"value\">406</elementName>",
				"						<elementName att=\"value\">407</elementName>",
				"						<elementName att=\"value\">408</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">409</elementName>",
				"						<elementName att=\"value\">410</elementName>",
				"						<elementName att=\"value\">411</elementName>",
				"						<elementName att=\"value\">412</elementName>",
				"						<elementName att=\"value\">413</elementName>",
				"						<elementName att=\"value\">414</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">415</elementName>",
				"						<elementName att=\"value\">416</elementName>",
				"						<elementName att=\"value\">417</elementName>",
				"						<elementName att=\"value\">418</elementName>",
				"						<elementName att=\"value\">419</elementName>",
				"						<elementName att=\"value\">420</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">421</elementName>",
				"						<elementName att=\"value\">422</elementName>",
				"						<elementName att=\"value\">423</elementName>",
				"						<elementName att=\"value\">424</elementName>",
				"						<elementName att=\"value\">425</elementName>",
				"						<elementName att=\"value\">426</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">427</elementName>",
				"						<elementName att=\"value\">428</elementName>",
				"						<elementName att=\"value\">429</elementName>",
				"						<elementName att=\"value\">430</elementName>",
				"						<elementName att=\"value\">431</elementName>",
				"						<elementName att=\"value\">432</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">433</elementName>",
				"						<elementName att=\"value\">434</elementName>",
				"						<elementName att=\"value\">435</elementName>",
				"						<elementName att=\"value\">436</elementName>",
				"						<elementName att=\"value\">437</elementName>",
				"						<elementName att=\"value\">438</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">439</elementName>",
				"						<elementName att=\"value\">440</elementName>",
				"						<elementName att=\"value\">441</elementName>",
				"						<elementName att=\"value\">442</elementName>",
				"						<elementName att=\"value\">443</elementName>",
				"						<elementName att=\"value\">444</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">445</elementName>",
				"						<elementName att=\"value\">446</elementName>",
				"						<elementName att=\"value\">447</elementName>",
				"						<elementName att=\"value\">448</elementName>",
				"						<elementName att=\"value\">449</elementName>",
				"						<elementName att=\"value\">450</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">451</elementName>",
				"						<elementName att=\"value\">452</elementName>",
				"						<elementName att=\"value\">453</elementName>",
				"						<elementName att=\"value\">454</elementName>",
				"						<elementName att=\"value\">455</elementName>",
				"						<elementName att=\"value\">456</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">457</elementName>",
				"						<elementName att=\"value\">458</elementName>",
				"						<elementName att=\"value\">459</elementName>",
				"						<elementName att=\"value\">460</elementName>",
				"						<elementName att=\"value\">461</elementName>",
				"						<elementName att=\"value\">462</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">463</elementName>",
				"						<elementName att=\"value\">464</elementName>",
				"						<elementName att=\"value\">465</elementName>",
				"						<elementName att=\"value\">466</elementName>",
				"						<elementName att=\"value\">467</elementName>",
				"						<elementName att=\"value\">468</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">469</elementName>",
				"						<elementName att=\"value\">470</elementName>",
				"						<elementName att=\"value\">471</elementName>",
				"						<elementName att=\"value\">472</elementName>",
				"						<elementName att=\"value\">473</elementName>",
				"						<elementName att=\"value\">474</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">475</elementName>",
				"						<elementName att=\"value\">476</elementName>",
				"						<elementName att=\"value\">477</elementName>",
				"						<elementName att=\"value\">478</elementName>",
				"						<elementName att=\"value\">479</elementName>",
				"						<elementName att=\"value\">480</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"			<elementName att=\"value\">", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">481</elementName>",
				"						<elementName att=\"value\">482</elementName>",
				"						<elementName att=\"value\">483</elementName>",
				"						<elementName att=\"value\">484</elementName>",
				"						<elementName att=\"value\">485</elementName>",
				"						<elementName att=\"value\">486</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">487</elementName>",
				"						<elementName att=\"value\">488</elementName>",
				"						<elementName att=\"value\">489</elementName>",
				"						<elementName att=\"value\">490</elementName>",
				"						<elementName att=\"value\">491</elementName>",
				"						<elementName att=\"value\">492</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">493</elementName>",
				"						<elementName att=\"value\">494</elementName>",
				"						<elementName att=\"value\">495</elementName>",
				"						<elementName att=\"value\">496</elementName>",
				"						<elementName att=\"value\">497</elementName>",
				"						<elementName att=\"value\">498</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">499</elementName>",
				"						<elementName att=\"value\">500</elementName>",
				"						<elementName att=\"value\">501</elementName>",
				"						<elementName att=\"value\">502</elementName>",
				"						<elementName att=\"value\">503</elementName>",
				"						<elementName att=\"value\">504</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">505</elementName>",
				"						<elementName att=\"value\">506</elementName>",
				"						<elementName att=\"value\">507</elementName>",
				"						<elementName att=\"value\">508</elementName>",
				"						<elementName att=\"value\">509</elementName>",
				"						<elementName att=\"value\">510</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">511</elementName>",
				"						<elementName att=\"value\">512</elementName>",
				"						<elementName att=\"value\">513</elementName>",
				"						<elementName att=\"value\">514</elementName>",
				"						<elementName att=\"value\">515</elementName>",
				"						<elementName att=\"value\">516</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">517</elementName>",
				"						<elementName att=\"value\">518</elementName>",
				"						<elementName att=\"value\">519</elementName>",
				"						<elementName att=\"value\">520</elementName>",
				"						<elementName att=\"value\">521</elementName>",
				"						<elementName att=\"value\">522</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">523</elementName>",
				"						<elementName att=\"value\">524</elementName>",
				"						<elementName att=\"value\">525</elementName>",
				"						<elementName att=\"value\">526</elementName>",
				"						<elementName att=\"value\">527</elementName>",
				"						<elementName att=\"value\">528</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">529</elementName>",
				"						<elementName att=\"value\">530</elementName>",
				"						<elementName att=\"value\">531</elementName>",
				"						<elementName att=\"value\">532</elementName>",
				"						<elementName att=\"value\">533</elementName>",
				"						<elementName att=\"value\">534</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">535</elementName>",
				"						<elementName att=\"value\">536</elementName>",
				"						<elementName att=\"value\">537</elementName>",
				"						<elementName att=\"value\">538</elementName>",
				"						<elementName att=\"value\">539</elementName>",
				"						<elementName att=\"value\">540</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">541</elementName>",
				"						<elementName att=\"value\">542</elementName>",
				"						<elementName att=\"value\">543</elementName>",
				"						<elementName att=\"value\">544</elementName>",
				"						<elementName att=\"value\">545</elementName>",
				"						<elementName att=\"value\">546</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">547</elementName>",
				"						<elementName att=\"value\">548</elementName>",
				"						<elementName att=\"value\">549</elementName>",
				"						<elementName att=\"value\">550</elementName>",
				"						<elementName att=\"value\">551</elementName>",
				"						<elementName att=\"value\">552</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">553</elementName>",
				"						<elementName att=\"value\">554</elementName>",
				"						<elementName att=\"value\">555</elementName>",
				"						<elementName att=\"value\">556</elementName>",
				"						<elementName att=\"value\">557</elementName>",
				"						<elementName att=\"value\">558</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">559</elementName>",
				"						<elementName att=\"value\">560</elementName>",
				"						<elementName att=\"value\">561</elementName>",
				"						<elementName att=\"value\">562</elementName>",
				"						<elementName att=\"value\">563</elementName>",
				"						<elementName att=\"value\">564</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">565</elementName>",
				"						<elementName att=\"value\">566</elementName>",
				"						<elementName att=\"value\">567</elementName>",
				"						<elementName att=\"value\">568</elementName>",
				"						<elementName att=\"value\">569</elementName>",
				"						<elementName att=\"value\">570</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">571</elementName>",
				"						<elementName att=\"value\">572</elementName>",
				"						<elementName att=\"value\">573</elementName>",
				"						<elementName att=\"value\">574</elementName>",
				"						<elementName att=\"value\">575</elementName>",
				"						<elementName att=\"value\">576</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">577</elementName>",
				"						<elementName att=\"value\">578</elementName>",
				"						<elementName att=\"value\">579</elementName>",
				"						<elementName att=\"value\">580</elementName>",
				"						<elementName att=\"value\">581</elementName>",
				"						<elementName att=\"value\">582</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">583</elementName>",
				"						<elementName att=\"value\">584</elementName>",
				"						<elementName att=\"value\">585</elementName>",
				"						<elementName att=\"value\">586</elementName>",
				"						<elementName att=\"value\">587</elementName>",
				"						<elementName att=\"value\">588</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">589</elementName>",
				"						<elementName att=\"value\">590</elementName>",
				"						<elementName att=\"value\">591</elementName>",
				"						<elementName att=\"value\">592</elementName>",
				"						<elementName att=\"value\">593</elementName>",
				"						<elementName att=\"value\">594</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">595</elementName>",
				"						<elementName att=\"value\">596</elementName>",
				"						<elementName att=\"value\">597</elementName>",
				"						<elementName att=\"value\">598</elementName>",
				"						<elementName att=\"value\">599</elementName>",
				"						<elementName att=\"value\">600</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"			<elementName att=\"value\">", "				<elementName att=\"value\">",
				"					<elementName att=\"value\">",
				"						<elementName att=\"value\">601</elementName>",
				"						<elementName att=\"value\">602</elementName>",
				"						<elementName att=\"value\">603</elementName>",
				"						<elementName att=\"value\">604</elementName>",
				"						<elementName att=\"value\">605</elementName>",
				"						<elementName att=\"value\">606</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">607</elementName>",
				"						<elementName att=\"value\">608</elementName>",
				"						<elementName att=\"value\">609</elementName>",
				"						<elementName att=\"value\">610</elementName>",
				"						<elementName att=\"value\">611</elementName>",
				"						<elementName att=\"value\">612</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">613</elementName>",
				"						<elementName att=\"value\">614</elementName>",
				"						<elementName att=\"value\">615</elementName>",
				"						<elementName att=\"value\">616</elementName>",
				"						<elementName att=\"value\">617</elementName>",
				"						<elementName att=\"value\">618</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">619</elementName>",
				"						<elementName att=\"value\">620</elementName>",
				"						<elementName att=\"value\">621</elementName>",
				"						<elementName att=\"value\">622</elementName>",
				"						<elementName att=\"value\">623</elementName>",
				"						<elementName att=\"value\">624</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">625</elementName>",
				"						<elementName att=\"value\">626</elementName>",
				"						<elementName att=\"value\">627</elementName>",
				"						<elementName att=\"value\">628</elementName>",
				"						<elementName att=\"value\">629</elementName>",
				"						<elementName att=\"value\">630</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">631</elementName>",
				"						<elementName att=\"value\">632</elementName>",
				"						<elementName att=\"value\">633</elementName>",
				"						<elementName att=\"value\">634</elementName>",
				"						<elementName att=\"value\">635</elementName>",
				"						<elementName att=\"value\">636</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">637</elementName>",
				"						<elementName att=\"value\">638</elementName>",
				"						<elementName att=\"value\">639</elementName>",
				"						<elementName att=\"value\">640</elementName>",
				"						<elementName att=\"value\">641</elementName>",
				"						<elementName att=\"value\">642</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">643</elementName>",
				"						<elementName att=\"value\">644</elementName>",
				"						<elementName att=\"value\">645</elementName>",
				"						<elementName att=\"value\">646</elementName>",
				"						<elementName att=\"value\">647</elementName>",
				"						<elementName att=\"value\">648</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">649</elementName>",
				"						<elementName att=\"value\">650</elementName>",
				"						<elementName att=\"value\">651</elementName>",
				"						<elementName att=\"value\">652</elementName>",
				"						<elementName att=\"value\">653</elementName>",
				"						<elementName att=\"value\">654</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">655</elementName>",
				"						<elementName att=\"value\">656</elementName>",
				"						<elementName att=\"value\">657</elementName>",
				"						<elementName att=\"value\">658</elementName>",
				"						<elementName att=\"value\">659</elementName>",
				"						<elementName att=\"value\">660</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">661</elementName>",
				"						<elementName att=\"value\">662</elementName>",
				"						<elementName att=\"value\">663</elementName>",
				"						<elementName att=\"value\">664</elementName>",
				"						<elementName att=\"value\">665</elementName>",
				"						<elementName att=\"value\">666</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">667</elementName>",
				"						<elementName att=\"value\">668</elementName>",
				"						<elementName att=\"value\">669</elementName>",
				"						<elementName att=\"value\">670</elementName>",
				"						<elementName att=\"value\">671</elementName>",
				"						<elementName att=\"value\">672</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">673</elementName>",
				"						<elementName att=\"value\">674</elementName>",
				"						<elementName att=\"value\">675</elementName>",
				"						<elementName att=\"value\">676</elementName>",
				"						<elementName att=\"value\">677</elementName>",
				"						<elementName att=\"value\">678</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">679</elementName>",
				"						<elementName att=\"value\">680</elementName>",
				"						<elementName att=\"value\">681</elementName>",
				"						<elementName att=\"value\">682</elementName>",
				"						<elementName att=\"value\">683</elementName>",
				"						<elementName att=\"value\">684</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">685</elementName>",
				"						<elementName att=\"value\">686</elementName>",
				"						<elementName att=\"value\">687</elementName>",
				"						<elementName att=\"value\">688</elementName>",
				"						<elementName att=\"value\">689</elementName>",
				"						<elementName att=\"value\">690</elementName>",
				"					</elementName>", "				</elementName>",
				"				<elementName att=\"value\">", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">691</elementName>",
				"						<elementName att=\"value\">692</elementName>",
				"						<elementName att=\"value\">693</elementName>",
				"						<elementName att=\"value\">694</elementName>",
				"						<elementName att=\"value\">695</elementName>",
				"						<elementName att=\"value\">696</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">697</elementName>",
				"						<elementName att=\"value\">698</elementName>",
				"						<elementName att=\"value\">699</elementName>",
				"						<elementName att=\"value\">700</elementName>",
				"						<elementName att=\"value\">701</elementName>",
				"						<elementName att=\"value\">702</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">703</elementName>",
				"						<elementName att=\"value\">704</elementName>",
				"						<elementName att=\"value\">705</elementName>",
				"						<elementName att=\"value\">706</elementName>",
				"						<elementName att=\"value\">707</elementName>",
				"						<elementName att=\"value\">708</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">709</elementName>",
				"						<elementName att=\"value\">710</elementName>",
				"						<elementName att=\"value\">711</elementName>",
				"						<elementName att=\"value\">712</elementName>",
				"						<elementName att=\"value\">713</elementName>",
				"						<elementName att=\"value\">714</elementName>",
				"					</elementName>", "					<elementName att=\"value\">",
				"						<elementName att=\"value\">715</elementName>",
				"						<elementName att=\"value\">716</elementName>",
				"						<elementName att=\"value\">717</elementName>",
				"						<elementName att=\"value\">718</elementName>",
				"						<elementName att=\"value\">719</elementName>",
				"						<elementName att=\"value\">720</elementName>",
				"					</elementName>", "				</elementName>", "			</elementName>",
				"		</elementName>", "	</elementName>", "</elementName>" };
		try {
			write2file(xmlseq);
			final long[] r = testConsume();
			assertTrue(r[0] == 874);
			assertTrue(r[1] == 874);
			assertTrue(r[2] == 259560);
		} catch (final IOException e) {
			e.printStackTrace();
			fail(e.toString());
		} catch (final XmlInvalidLtException e) {
			e.printStackTrace();
			fail(e.toString());
		}
	}

	private long[] testConsume()
			throws XmlInvalidLtException, UnsupportedEncodingException, FileNotFoundException, IOException {
		final long[] result = { 0L, 0L, 0L };
		final XmlConsumer consumer = new XmlConsumer(
				new InputStreamReader(new FileInputStream(this.fileName), "UTF-8"));
		final String attName = "att";
		final StringBuilder att = new StringBuilder();
		final StringBuilder value = new StringBuilder();
		while (!consumer.isAlreadyConsumedEndTagElementRoot()) {
			if (consumer.isNextTagOpen() && !consumer.isNextTagOpenClose()) {
				// elements number
				result[0]++;
				consumer.consumeTag();
				att.setLength(0);
				consumer.getElementAttributeValue(att, attName);
				// attributes equals to 'value'
				if (att.toString().equals("value")) {
					result[1]++;
				}
				if (consumer.isNextTagClose()) {
					value.setLength(0);
					consumer.getElementValue(value);
					// sum of all values
					try {
						if (att.toString().equals("value")) {
							result[2] = result[2] + Long.valueOf(value.toString());
						}
					} catch (final NumberFormatException e) {
						/* ignored */
					}
				}
			} else {
				consumer.consumeTag();
			}
		}
		consumer.close();
		return result;
	}

	private void write2file(final String[] txt) throws IOException {
		final BufferedWriter bw = new BufferedWriter(
				new OutputStreamWriter(new FileOutputStream(this.fileName, false), "UTF-8"));
		for (int i = 0; i < txt.length; i++) {
			bw.write(txt[i]);
			bw.write('\n');
		}
		bw.close();
	}

}
